### ISSUE TITLE
 STMF411 cannot be compiled

### ISSUE THREAD

**Issue by 01Space** [p-fpv/FC-stm32f411ceu6-stm32f405vgt6-inav-betaflight#1]
Generating STMF411/settings_generated.h, STMF411/settings_generated.c
Scanning dependencies of target STMF411.elf
Building ASM object src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/__/__/startup/startup_stm32f411xe.s.obj
Building C object src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/__/__/drivers/bus_spi.c.obj
Building C object src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/__/__/drivers/serial_uart.c.obj
Building C object src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/__/system_stm32f4xx.c.obj
/mnt/c/inav/src/main/target/system_stm32f4xx.c:382:10: error: #error Invalid HSE_VALUE
  382 |         #error Invalid HSE_VALUE
      |          ^~~~~
/mnt/c/inav/src/main/target/system_stm32f4xx.c: In function 'SetSysClock':
/mnt/c/inav/src/main/target/system_stm32f4xx.c:700:20: error: 'PLL_M' undeclared (first use in this function); did you mean 'PLL_P'?
  700 |     RCC->PLLCFGR = PLL_M | (PLL_N << 6) | (((PLL_P >> 1) -1) << 16) |
      |                    ^~~~~
      |                    PLL_P
/mnt/c/inav/src/main/target/system_stm32f4xx.c:700:20: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/build.make:102: src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/__/system_stm32f4xx.c.obj] Error 1
make[2]: *** [CMakeFiles/Makefile2:64678: src/main/target/STM32F411/CMakeFiles/STMF411.elf.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:64631: src/main/target/STM32F411/CMakeFiles/STMF411.dir/rule] Error 2
make: *** [Makefile:27860: STMF411] Error 2

**Comment by p-fpv** [comment]
Need a modified firmware, for example, this https://github.com/p-fpv/inav/releases   
In [README.md](https://github.com/p-fpv/FC-stm32f411ceu6-stm32f405vgt6-inav-betaflight#readme) there is also a link.
The original firmware supports only quartz with frequencies of 24, 16, 8 mhz.  
https://github.com/p-fpv/inav/blob/6.0.0-ppm-mpu6050/src/main/target/system_stm32f4xx.c#L375

**Comment by 01Space** [comment]
thank you! I just compiled it successfully
